FROM node:12.19.0-alpine

# set /app as working directory on the VM
WORKDIR "/app"

# copy package.json
COPY package.json .

# install deps
RUN npm install

# copy over everything else
COPY . .

# run start
CMD ["npm", "run", "start"]
