apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: markweldonbrewer/checktheflows_api:1.8
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: develop
            - name: MONGO_DB
              value: check-the-flows
            - name: MONGO_USERNAME
              value: MWBrewer
            - name: MONGO_PORT
              value: '29946'
            - name: MONGO_HOST
              value: '129946'
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongopassword
                  key: MONGO_PASSWORD
