apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: rivercollective-com-tls
spec:
  secretName: rivercollective-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rivercollective.com
  dnsNames:
    - rivercollective.com
    - www.rivercollective.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - rivercollective.com
          - www.rivercollective.com
