apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: rivercollective-com-tls
  namespace: default
spec:
  secretName: rivercollective-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rivercollective.com
  dnsNames:
  - rivercollective.com
  - www.rivercollective.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
        - rivercollective.com
        - www.rivercollective.com
